### PR TITLE
woodall.cpp

### PR DESCRIPTION
**Pull request by harrypotter0**
A Woodall number is of the form:

Wn = n.2n – 1 whose program has been added in c++ .

### CODE REVIEW

**Comment by Ir1d** [comment]
@harrypotter0 ???

**Comment by Dev-XYS** [comment]
&emsp;&emsp;I am more than happy to see someone actually sends a pull request to this repository, but I regret to tell you that your pull request will not be merged because I do not accept any pull requests at present. (Declared as "我们不赞成Pull Requests" in README, which means "we do not accept pull requests".)
&emsp;&emsp;You can keep your contribution as part of your forked repository, and, all contents of *Algorithms* can be used for any purpose under *The Unlicense*.

**Comment by Dev-XYS** [comment]
&emsp;&emsp;Hello @harrypotter0 !
&emsp;&emsp;I have just learnt how to create and manage branches with Git, and I'd like to merge all others' contributions into another newly-created branch. Maybe the branch will be “candidate".

**Comment by harrypotter0** [comment]
Thanks for the merge @Dev-XYS  I would love to contribute more newer algorithms and optimized ones in future to your repository . Thanks for the acceptance :+1:

**Pull request merged**
